name: cloud-photoalbum

services:
  db:
    image: postgres:18-alpine
    container_name: photoalbum-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photoalbum
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # healthceck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d photoalbum"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: photoalbum-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@photoalbum.hu
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5055:80"
    depends_on:
      db:
        # healthcheck is ok
        condition: service_healthy

volumes:
  pgdata: