name: Build .NET and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 1. Angular Build 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.16'
    - name: Install dependencies and Build Angular
      working-directory: ./photoalbum-fe
      run: |
        npm install
        npm run build

    # 2. .NET Build 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0'
    - name: Restore dependencies and Build .NET
      working-directory: ./photoalbum-be
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Release